### ISSUE TITLE
Request for Python dependencies list

### ISSUE THREAD

**Issue by christabella** [yashkant/Model-Inversion-Attack#1]
Thank you for the notebook. However, I am unable to replicate the environment and running into a lot of compatibility issues. The only thing I am able to surmise from the source code is that it is using Python 2.7.12.

May I know the exact versions of the packages, e.g. Pylearn2, Theano, that you are using? Thank you!

**Comment by christabella** [comment]
I have gotten it working with:

```
conda create --name pylearn2 python=2.7.13
conda activate pylearn2
conda install -c anaconda jupyter
conda install -c anaconda notebook
pip install Theano==0.6.0 Pillow matplotlib
```
And installing pylearn2 from source.

What did not work:
```
conda install -c anaconda pylearn2
conda install -c anaconda theano==0.8.2
```

**Comment by theGreatRaphael** [comment]
Hi, thanks for the notebook.
And thanks for the environment instructions.
Do you remember which tensorflow version you used?

**Comment by zer0-1s** [comment]
so how to get pylearn2?

**Comment by sxt999** [comment]
git clone git://github.com/lisa-lab/pylearn2.git 
cd pylearn2
python setup.py develop --user

**Comment by JsphByd** [comment]
How did you install tensorflow in a python2.7 environment? Tensorflow is not supported by python2.
